set-option global startup_info_version 20180413
set-option global ui_options ncurses_assistant=none
addhl global/ number-lines
colorscheme zenburn
source ~/.config/kak/fuzzy.kak


## LSP SETUP
eval %sh{kak-lsp --kakoune -s $kak_session }
nop %sh{ (kak-lsp -s $kak_session -vvv ) > /dev/null 2>&1 < /dev/null & }
# display info inline
set global lsp_hover_anchor true

# Quick access for common commands
map -docstring "query type under cursor" global user t :lsp-hover<ret>
map -docstring "jump to another buffer" global user b :fuzzy-buffer<ret>
map -docstring "jump to another file" global user e :fuzzy-edit<ret>

# Use rg instead of grep -rHn
set-option global grepcmd rg

# Haskell: use stylish-haskell as formatter
hook global BufWritePre .*[.](hs) %{
  set-option buffer formatcmd stylish-haskell
  format 
}

# Old habits die hard
alias global x write-quit
alias global xa write-all-quit

# Try reading project-specific config files
try %{ source .kakrc.local }

map -docstring "[broken] hardwrap current selection" global user f "|fmt -w%opt{autowrap_column}<ret>"

# Enable soft-wrapping
add-highlighter global/ wrap -word -indent -width 180 -marker ' ↪ '
# Display hidden chars
add-highlighter global/ show-whitespaces -spc ' ' -lf ' ' -nbsp '·'

hook global NormalKey y|d|c %{ nop %sh{
  #printf %s "$kak_reg_dquote" | sed "s/''/'/g" | sed "s/\(^'\|'$\)//g" | xsel --input --primary
  printf %s "$kak_main_reg_dquote" | xsel --input --primary
}}

# Use tab to cycle through completion results
hook global InsertCompletionShow .* %{ map window insert <tab> <c-n>; map window insert <s-tab> <c-p> }
hook global InsertCompletionHide .* %{ unmap window insert <tab> <c-n>; unmap window insert <s-tab> <c-p> }

# use spaces instead of tabs
map global insert <tab> '<a-;><gt>'
map global insert <s-tab> '<a-;><lt>'
